"""Packaging sanity: every file the installers reference must exist and the
metadata must stay consistent — this is what CI can check without a Windows
box or a Debian machine."""

import re
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
ISS = ROOT / "packaging" / "windows" / "hushkey.iss"
DEB = ROOT / "packaging" / "linux"


def test_iss_sources_all_exist():
    """Every [Files] Source path must resolve — iscc would fail on a missing one."""
    text = ISS.read_text(encoding="utf-8")
    sources = re.findall(r'^Source: "([^"]+)"', text, flags=re.M)
    assert sources, "no [Files] entries found"
    missing = [s for s in sources
               if s != "logo.ico"  # generated by make_ico.py in CI
               and not (ISS.parent / s).resolve().exists()]
    assert not missing, f"missing installer payloads: {missing}"


def test_iss_mentions_every_runtime_file():
    """The Windows payload must mirror what install.ps1 needs at runtime."""
    text = ISS.read_text(encoding="utf-8")
    for needed in ("dictate.py", "tray.py", "recorder.py", "transcribe.py",
                   "install.ps1", "uninstall.ps1", "requirements.txt",
                   "requirements-gpu.txt", "assets\\logo.png"):
        assert needed in text, f"{needed} not packed by hushkey.iss"


def test_iss_uninstalls_and_verifies_properly():
    text = ISS.read_text(encoding="utf-8")
    assert "-Purge" in text              # UninstallRun must also drop the venv
    assert "ArchitecturesAllowed" in text
    assert "SHA256" in text              # python.org fallback is checksum-pinned


def test_deb_payload_matches_install_sh_expectations():
    """install.sh reads systemd/*.service.in and udev/*.rules — the deb must ship them."""
    script = (DEB / "build-deb.sh").read_text(encoding="utf-8")
    assert "systemd/" in script and "udev/" in script
    assert "assets/logo.png" in script
    assert "install.sh" in script and "uninstall.sh" in script


def test_deb_control_has_mandatory_fields():
    control = (DEB / "control.in").read_text(encoding="utf-8")
    for field in ("Package:", "Version:", "Architecture:", "Maintainer:",
                  "Description:", "Depends:"):
        assert field in control, f"{field} missing in control.in"
    assert "python3 (>= 3.10)" in control


def test_packaging_shell_scripts_parse():
    """bash -n for every shipped shell script (works on any CI OS)."""
    import subprocess
    for script in [DEB / "build-deb.sh", DEB / "postinst", DEB / "prerm", DEB / "postrm"]:
        # relative path + cwd: keeps working whether "bash" is Git Bash or WSL
        subprocess.run(["bash", "-n", script.relative_to(ROOT).as_posix()],
                       cwd=ROOT, check=True)


def test_release_workflow_builds_on_tags_and_smoke_tests_prs():
    wf = (ROOT / ".github" / "workflows" / "release.yml").read_text(encoding="utf-8")
    assert 'tags: ["v*"]' in wf           # real builds happen on version tags
    assert "pull_request:" in wf          # packaging changes smoke-build in PRs
    assert "ISCC.exe" in wf               # windows installer actually compiles
    assert "build-deb.sh" in wf           # deb actually builds
